### ISSUE TITLE
EOL'ing .NET Core support?

### ISSUE THREAD

**Issue by omajid** [fabric8-launcher/launcher-application#1029]
### Description

The .NET team at Red Hat contributed support for .NET Core support to the launcher in 2019.

However, a few things have happened since then:

- .NET Core 2.2 was End-of-Life'd. It has known unpatched security vulernatiblites.
- .NET Core 3.1 has been released and is the latest and best version to use so far.
- The launcher was completely re-written in a new language
- The .NET Core project in launcher was slightly broken and remained broken for at least a few months. It seems to be better now, though.
  - It wasn't possible to create a datbase-using .NET Core backend
  - Now I get a download link that just doesn't work and gives me a blank page instead of a zip download
- The launcher development model was completely changed, making it very difficult for us to modify/test things.
- We haven't seen any data or analysis indicating this is something worth prioritizing for our team (more difficult because of our team not being Java+Quarkus+OpenShift experts)

We would like to make it clearer to users that this is basically unmaintained and probably doesn't work. Preferably we would like to remove this instead of causing users pain.

To that end, we think this should be deprecated or removed. Failing that, we want to make it clear that our team can't continue to own or maintain this.

### What should happen?

- Users get an up-to-date version of .NET Core backends

### What happens instead?

Users get a less-than-stellar experience:

- Users get errors or a non-functional project
- Users get a .NET Core project that's been out of support for months and has known unpatched security vulnerabilities.
- Users should instead get a new project based on the latest .NET Core LTS version

### Proposal

Some options:

- Lets remove .NET Core support
- Transition testing/support of .NET Core to someone else

cc @Bob-Davis @dbhole @tmds

**Comment by quintesse** [comment]
Although I don't disagree at all with the proposed removal I do want to clarify two of the points that were made:

 - The launcher was completely re-written in a new language
 - The launcher development model was completely changed, making it very difficult for us to modify/test things.

Now first of all perhaps .NET 3 is so different from .NET 2 that the example code that was added to the Launcher has to be completely rewritten. That could indeed mean an investment of time that is not worth making.

Also it might be that the Creator flow gets removed from the Launcher entirely. Which is also a good reason not to invest more time.

And yes, the Launcher was rewritten and the development model was changed.

But those changes have made contributing to the Launcher much much easier. No programming is necessary anymore when adding support for languages or features (so the language the Launcher is written in is mostly irrelevant), while testing has basically remained the same.

And seeing that updates for existing runtimes tend to be 2-3 line changes suggests that keeping something running in the Launcher is very low-maintenance.

**Comment by tmds** [comment]
@quintesse has .NET Core 2.2 support been removed from the launcher? The application that is generated by the launcher is broken, and 2.2 is EOL.

**Comment by quintesse** [comment]
@tmds the relevant feature for generating applications has been hidden permanently from the Launcher UI. So, no it hasn't been removed, but usrs won't be able to generate applications anymore, for .NET or any other runtime.

**Comment by tmds** [comment]
> usrs won't be able to generate applications anymore, for .NET or any other runtime.

@omajid is that enough for closing this?

**Comment by omajid** [comment]
Yes, that works for me.
