### ISSUE TITLE
Default port usage 

### ISSUE THREAD

**Issue by akondasif** [fabric8-launcher/launcher-application#1032]
### Description

Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of default port usage. According to a recent report default port usages must be avoided: https://www.bleepingcomputer.com/news/security/most-cyber-attacks-focus-on-just-three-tcp-ports/#:~:text=According%20to%20the%20report%2C%20the,(Hypertext%20Transfer%20Protocol%20Secure)

### What should happen?

Default ports should be avoided 

### What happens instead?

Default ports are used 

Source: https://github.com/fabric8-launcher/launcher-application/blob/master/services/openshift-service-impl/src/test/resources/service.cache.yml 

Suggested fix: https://github.com/fabric8-launcher/launcher-application/pull/1031 

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by quintesse** [comment]
This is not useful. Just a couple of trivial warnings and in this case completely unwarranted. Just noise basically.
