### ISSUE TITLE
Change name of repository

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-application#829]
Now that we unified the repositories the name `launcher-backend` doesn't make much sense anymore, we should change it.

Just `launcher`? `launcher-service`? `app-launcher`?

**Comment by gastaldi** [comment]
My first thought was to rename it to `launcher` only as this would be the repository for issues and code, but I like `launcher-service` and `launcher-app`, so I'll love to listen to your thoughts before we do that

**Comment by gastaldi** [comment]
Renamed to `launcher-application`. Closing
