### ISSUE TITLE
Enable user tracking

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-application#881]
Container issue to chart where tracking should be enabled:

* appdev-documentation (JS)
* launchpad-frontend (JS)
* launchpad-missioncontrol (server-sent events)
* launchpad-backend (server-sent events)

**Comment by rdruss** [comment]
Do we have any usage information for Launcher?

**Comment by gastaldi** [comment]
Yes, we have Google Analytics running in https://analytics.google.com/analytics/web/?authuser=1#/a147061038w209108414p201375122. Added you as a user to visualize it. Closing this issue
