### ISSUE TITLE
Remove support for OpenShift 3.11 Starter clusters

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-application#892]
The OpenShift 3.11 starter clusters are no longer available and it's impossible to signup for the existing ones. 

We need to support OpenShift 4.x (#832) and enable deployment in `Starter OCP4: US West (Oregon)` if our plan is to still support starter clusters

**Comment by gastaldi** [comment]
@npfr we need your input here: Should we still support Starter clusters? If so, we need to fit the support for OpenShift 4.x  into our roadmap

**Comment by paulrobinson** [comment]
(FYI, I use this Github handle)

Lets take this offline, I don't have a clear answer on this yet.

**Comment by gastaldi** [comment]
Closing as the Starter clusters will still exist (based on the last All-Hands meeting). We still need to support OpenShift 4.x though
