### ISSUE TITLE
README.md when selecting all capabilities for Vert.x 3.7.1 is empty

### ISSUE THREAD

**Issue by huntley** [fabric8-launcher/launcher-application#894]
### Description
When using the Create New Application flow for Vert.x 3.7.1 (could affect other backends) and selecting the all of the capabilities, the README.md in the zip file is empty except for:
```
# rest-vertx

Created by the Cloud App Generator
```

...

### What should happen?
I would expect to see a single README that provides information about how to build and deploy the application. Or, if glomming them all together isn't feasible, separate READMEs for each capability.
...

### What happens instead?

...

### Do you have any idea why?

...

### Error log

```
If you have an error log, please paste it here.
```

**Comment by quintesse** [comment]
Good catch, thanks @huntley
