### ISSUE TITLE
Authorize link for Git destination repository is not generated correctly

### ISSUE THREAD

**Issue by JameelB** [fabric8-launcher/launcher-application#930]
### Description
The `Authorize` link in the Destination Repository does not get set to the correct link when a Github provider is configured in Keycloak.

![image](https://user-images.githubusercontent.com/9078522/62870481-9eedf780-bd11-11e9-8f1d-6c87aaa4d210.png)

### What should happen?
If a Github provider is configured, the link should direct to the Github OAuth endpoint instead of `https://managed.openshift.com`.

### What happens instead?
The Github Authorize link always directs to `https://managed.openshift.com` whether there's a Github provider configured or not.

### Do you have any idea why?
The action for generating the Authorization link doesn't seem to pass any provider/redirect to the function [generateAuthorizationLink](https://github.com/fabric8-launcher/launcher-application/blob/master/frontend/packages/launcher-app/src/hubs/dest-repository-hub.tsx#L26). Because of this, the Authorization link always gets directed to `https://manage.openshift.com/`.
https://github.com/fabric8-launcher/launcher-application/blob/master/frontend/packages/launcher-app/src/auth/impl/keycloak-authentication-api.ts#L125-L127

### Error log
N/A

**Comment by edewit** [comment]
setting the git provider in `git-provider.yaml` is only supported if the authentication is set to "openshift"

**Comment by JameelB** [comment]
Hi @edewit, is that a property to be configured in the configmap/custom resource?

**Comment by edewit** [comment]
@JameelB turns out that this was also an issue on our production server thanks for finding it. Solved it by adding 'github' as a default, but you can configure it to be 'gitea' as well. In the end it's just the name of the broker you setup in keycloak

**Comment by JameelB** [comment]
Thanks for resolving this issue so quickly @edewit!
