### ISSUE TITLE
OpenShift Console URL is incorrect after Launcher deploys an app to OCP4.x

### ISSUE THREAD

**Issue by VeerMuchandi** [fabric8-launcher/launcher-application#992]
### Description
Once the application is deployed by the Launcher, the `OpenShift Console` link takes to an error page. 
Note this location may be slightly different with 4.2 developer console.

### What should happen?
It should take to overview page with URL like
https://CONSOLE_URL/overview/ns/PROJECT_NAME
Note this location may be slightly different with 4.2 developer console.

### What happens instead?
It goes to https://CONSOLE_URL/console/project/PROJECT_NAME/overview/
and returns Error 404 Not found

### Do you have any idea why?
Update from 3.x to 4.x

### Error log

```
If you have an error log, please paste it here.
```

**Comment by edewit** [comment]
fixed in the operator https://github.com/fabric8-launcher/launcher-operator/pull/52 you can now add oauth api in the "cr"
