### ISSUE TITLE
Frontend application fails deployment

### ISSUE THREAD

**Issue by VeerMuchandi** [fabric8-launcher/launcher-application#995]
### Description

All three frontend applications fail deployment. The pods continue to crash loop.

### What should happen?

The frontend pod should come up

### What happens instead?

Events show readiness probe fails.

Also there are warnings like this in pod logs

```
Running as user uid=1000630000(1000630000) gid=0(root) groups=0(root),1000630000
Running this container is only recommended when running in test or development.
It is recommended to use this s2i image as a pure builder image and use it with an openshift chain build https://docs.okd.io/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds
command not found: serve
```

### Do you have any idea why?

...

### Error log

```
If you have an error log, please paste it here.
```

**Comment by quintesse** [comment]
It's a memory issue. For some reason the app uses more memory on his cluster and therefore `serve` won't start. The memory limits we set are obviously too tight.

I'll relax them, that should be okay now we're not targeting starter clusters anymore.
